spring.application.name=wedding-planner
spring.datasource.url=jdbc:postgresql://localhost:5432/planner
spring.datasource.username=planner_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect