spring.application.name=wedding-planner
spring.profiles.active=local

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

app.frontend.oauth-success-url=http://localhost:5173/oauth-success

stripe.secret.key=${STRIPE_SECRET_KEY:}
stripe.publishable.key=${STRIPE_PUBLISHABLE_KEY:}

